# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daily Apartment
author: Jack
description: There is no more miserable human being than one in whom nothing is habitual but indecision.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jayquinn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-whiteglass.gemspec
  - screenshot.png
  - vendor
  - project-boronia
# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:n능

